// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: duration.proto

#ifndef PROTOBUF_duration_2eproto__INCLUDED
#define PROTOBUF_duration_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace google {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_duration_2eproto();
void protobuf_AssignDesc_duration_2eproto();
void protobuf_ShutdownFile_duration_2eproto();

class Duration;

// ===================================================================

class Duration : public ::google::protobuf::Message {
 public:
  Duration();
  virtual ~Duration();

  Duration(const Duration& from);

  inline Duration& operator=(const Duration& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Duration& default_instance();

  void Swap(Duration* other);

  // implements Message ----------------------------------------------

  Duration* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Duration& from);
  void MergeFrom(const Duration& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 seconds = 1;
  inline bool has_seconds() const;
  inline void clear_seconds();
  static const int kSecondsFieldNumber = 1;
  inline ::google::protobuf::int64 seconds() const;
  inline void set_seconds(::google::protobuf::int64 value);

  // optional int32 nanos = 2;
  inline bool has_nanos() const;
  inline void clear_nanos();
  static const int kNanosFieldNumber = 2;
  inline ::google::protobuf::int32 nanos() const;
  inline void set_nanos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:google.protobuf.Duration)
 private:
  inline void set_has_seconds();
  inline void clear_has_seconds();
  inline void set_has_nanos();
  inline void clear_has_nanos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 seconds_;
  ::google::protobuf::int32 nanos_;
  friend void  protobuf_AddDesc_duration_2eproto();
  friend void protobuf_AssignDesc_duration_2eproto();
  friend void protobuf_ShutdownFile_duration_2eproto();

  void InitAsDefaultInstance();
  static Duration* default_instance_;
};
// ===================================================================


// ===================================================================

// Duration

// optional int64 seconds = 1;
inline bool Duration::has_seconds() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Duration::set_has_seconds() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Duration::clear_has_seconds() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Duration::clear_seconds() {
  seconds_ = GOOGLE_LONGLONG(0);
  clear_has_seconds();
}
inline ::google::protobuf::int64 Duration::seconds() const {
  // @@protoc_insertion_point(field_get:google.protobuf.Duration.seconds)
  return seconds_;
}
inline void Duration::set_seconds(::google::protobuf::int64 value) {
  set_has_seconds();
  seconds_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.Duration.seconds)
}

// optional int32 nanos = 2;
inline bool Duration::has_nanos() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Duration::set_has_nanos() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Duration::clear_has_nanos() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Duration::clear_nanos() {
  nanos_ = 0;
  clear_has_nanos();
}
inline ::google::protobuf::int32 Duration::nanos() const {
  // @@protoc_insertion_point(field_get:google.protobuf.Duration.nanos)
  return nanos_;
}
inline void Duration::set_nanos(::google::protobuf::int32 value) {
  set_has_nanos();
  nanos_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.Duration.nanos)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace google

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_duration_2eproto__INCLUDED
